Repository jujoycode/hydra, pull requests merged in 2024-12, with the labels that each got.

#2 Edit DB Convention
  docs/convention-db.md
Labels: enhancement

#3 오기 수정
  docs/convention-db.md
  docs/table-erd.md
Labels: documentation

#4 자잘한 문서 수정
  .github/ISSUE_TEMPLATE/1.bug_report.md
  .github/pull_request_template.md
  docs/kick-off.md
Labels: documentation

#5 :sparkles: 1.feature.md -> 설계된 기능을 등록하기 위한 탬플릿
  .github/ISSUE_TEMPLATE/1.feature.md
  .github/ISSUE_TEMPLATE/2.bug_report.md
  .github/ISSUE_TEMPLATE/3.feature_request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#6 ✨ 1.feature.md -> 설계된 기능을 등록하기 위한 탬플릿
  .github/ISSUE_TEMPLATE/1.feature.md
  .github/ISSUE_TEMPLATE/2.bug_report.md
  .github/ISSUE_TEMPLATE/3.feature_request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#10 Prisma ORM 적용 (#9 Solved)
  .gitignore
  electron.vite.config.ts
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  src/assets/hydra.png
  src/assets/icons/mac/hydra.icns
  src/main/core/base/CoreBase.ts
  src/main/core/base/CoreBaseHandler.ts
  src/main/core/constant/CoreConstant.ts
  src/main/core/database/CoreDataBase.ts
  src/main/core/interface/CoreInterface.ts
  src/main/core/util/CoreUtil.ts
  src/main/core/util/PrismaBaseUtil.ts
  src/main/core/util/SupabaseUtil.ts
  src/main/handler/initHandler.ts
  src/main/index.ts
  src/renderer/src/components/features/Navbar.tsx
  tsconfig.node.json
  tsconfig.web.json
Labels: enhancement, P1

#11 prisma 모듈 리팩토링
  electron.vite.config.ts
  package.json
  pnpm-lock.yaml
  src/main/core/database/CoreDataBase.ts
  src/main/core/database/prisma/schema.prisma
  src/main/core/lib/PrismaLib.ts
  src/main/core/lib/SupabaseLib.ts
  src/main/core/util/CoreUtil.ts
  tsconfig.node.json
Labels: enhancement

#12 Supabase Auth 개발 완료 (#8 Solved)
  src/main/core/base/CoreBaseHandler.ts
  src/main/core/database/prisma/schema.prisma
  src/main/core/interface/CoreInterface.ts
  src/main/handler/auth/DeleteUserHandler.ts
  src/main/handler/auth/GetSessionHandler.ts
  src/main/handler/auth/SignInWithOtpHandler.ts
  src/main/handler/auth/SignOutHandler.ts
  src/main/handler/auth/UpdateUserHandler.ts
  src/main/handler/auth/VerifyOtpTokenHandler.ts
  src/main/handler/initHandler.ts
Labels: enhancement, P2

#14 preload를 통한 ipc 인터페이스 공개 로직 추가
  electron.vite.config.ts
  src/main/core/interface/CoreInterface.ts
  src/preload/index.d.ts
  src/preload/index.ts
  tsconfig.node.json
  tsconfig.web.json
Labels: enhancement

#13 Supabase Auth와 Prisma Schema 통합 및 schema 파일 분리
  package.json
  src/main/core/database/prisma/schema/auth.prisma
  src/main/core/database/prisma/schema/public.prisma
  src/main/core/database/prisma/schema/schema.prisma
Labels: enhancement

#16 #Bugfix/15
  docs/kick-off.md
  src/main/core/base/CoreBaseHandler.ts
Labels: bug, P0

#20 :sparkles: SupabaseLib - Apply Singleton
  src/main/core/interface/CoreInterface.ts
  src/main/core/lib/SupabaseLib.ts
  src/main/handler/auth/DeleteUserHandler.ts
  src/main/handler/auth/GetSessionHandler.ts
  src/main/handler/auth/SignInWithOtpHandler.ts
  src/main/handler/auth/SignOutHandler.ts
  src/main/handler/auth/UpdateUserHandler.ts
  src/main/handler/auth/VerifyOtpTokenHandler.ts
  src/main/index.ts
Labels: enhancement, P3
